---
title: "Data manipulation in R (online workshop)"
author: "Sigrid Weber"
site: bookdown::bookdown_site
documentclass: book
output:
  bookdown::gitbook:
    config:
      sharing:
        facebook: false
        twitter: false
        all: []
  bookdown::pdf_book: default
---

# Introduction

Data manipulation - or the process of cleaning, organising and preparing your data for further analysis - is required for most projects involving real-world datasets. This workshop teaches you how to use R to manipulate raw data and prepare it for analysis. We will cover the following topics:

* The grammar of data manipulation
* Merging multiple datasets
* Creating subsets of data using filters
* Reshaping data between long and wide formats
* Summarising data with group-wise operation
* Setting up data pipelines in dplyr for efficient data manipulation


The workshop is designed for individuals who are already familiar with R but wish to learn efficient techniques for data manipulation. The workshop will be a combination of coding demonstrations by me and exercises for you to try on your own computer. Please make sure that R and RStudio are installed for the workshop. You may also want to install the package *tidyverse* in advance. Instructions how to do so can be found in the section *3 Getting started*.

Towards the end of the workshop, we will hopefully have time to discuss your dissertation projects and data challenges. Please feel free to reach out to me anytime after the workshop if you face specific problems manipulating your data for your research projects: <a href = "mailto: s.weber.17@ucl.ac.uk">s.weber.17@ucl.ac.uk</a>. 

